# Required
version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

# Image to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
